### ISSUE TITLE
Color days by leave type; colored bank holidays

### ISSUE THREAD

**Issue by jekuno** [timeoff-management/application#108]
**Suggestion**:
* Allow to choose a custom color for each leave type at settings/general/leave types. Use this color in calendar and team view. This cleans up the UI (e.g. holidays can be recognized by green background color, illnesses by red background color).
* You could also colorize bank holidays (which can already be entered in the background) in calendar and team view. (I suppose that's why you implemented this feature originally?!)

**Comment by filipjonckers** [comment]
This would make the app much more usable indeed.
- add custom color selection widget per leave type
- show custom color in calendar and team view and request handler
(different colors for sick days, work from home, training/course,  other office, etc...)
We still use excel (yes grrr) due to the auto coloring feature ... 
This would dramatically open up the usage of the app to not only leave days but any other day type overview/schedule.

Thanks for your great work !

**Comment by filipjonckers** [comment]
Just noticed that a color field is available in the sqlite database in the LeaveTypes table which is - I assume - connected to this ?
I changed the field value but it's not used yet.

**Comment by vpp** [comment]
hi @filipjonckers, yeah, there was some ground work done to bring this feature in, but it is not quite ready yet.

**Comment by bigheadsmith** [comment]
Agree with @filipjonckers, this feature would make the app much easier to use as we too currently use different colours in excel to give a visual key for different leave types (holiday, sickness, maternity/paternity, etc).
I could get the colours to show in the General Setting page, but I do not have enough knowledge (yet!) of nodejs to get them to show on calendar view.

**Comment by vpp** [comment]
@bigheadsmith thanks for feedback.

One of the issues for me (as I am not good front-end/designer person) would be to come up with about 10 colors that could be used as options for the leave tyoes highlights. That was one of the reasons why this feature stalled.

I would appreciate any suggestions (and examples) about colors to use in the app that would fit the existing colour schema.

**Comment by bigheadsmith** [comment]
Hi @vpp,
I'm not great at coming up with colours. A colour picker for the leave types would probably work best then the end user can choose whatever they like to use for each leave type, but I would have no idea how difficult this would be for you to implement.

I will give it a go though. My colour suggestions are below, forgive me as I mentioned I am in no way a designer or arty in any way

- Use #96c521 as generic holiday leave type.
- Use #ffcba4 for a sickness leave type.
- Use #cb6cac for a maternity/paternity leave type.
- Use a lighter shade for each of the above for when an absence request hasn't been approved yet (this link might help for calculating these colours dynamically https://www.sitepoint.com/javascript-generate-lighter-darker-color/)
- Change current day colour to be a grey colour like #61686b (matched to page title colour).
- Use #ac2a22 for unapproved absence (missing a day of work without a valid reason).
- Keep bank holiday as it it.
- and then a final colour for requesting unpaid time off (black?)

As for coming up with more colours, the more you add the more likely they are to clash, which is why I suggested a colour picker above  for the user. That way they can choose for themselves and won't bother you if they do not like the colour scheme :)

I found a few colour scheme generators around that might help a little
http://colormind.io
http://paletton.com

**Comment by filipjonckers** [comment]
Hi @vpp !

I would keep it simple - let the administrator choose their own colors (most flexible option, short development time).
At this time I would even say that a simple string input of a hexadecimal RGB value would be sufficient.
If you want to make it a bit fancier, show the color field in the same background color.

Example:
![example](https://user-images.githubusercontent.com/3816316/30068713-e0a81d8e-925e-11e7-9358-b4cb551dc10a.png)

**Comment by vpp** [comment]
@filipjonckers fair suggestion

**Comment by gavin20** [comment]
Hello I'm following up on this request. Does anyone know which files to edit in the General view to enable? And has anyone made progress to show colored leaves within the calendar and team view page?

**Comment by krin-san** [comment]
Any updates on this feature? Would love to have it for our team.

**Comment by iainhallam** [comment]
If you're looking for a set of colours, why not try Google's Material Design guide or Microsoft's Metro? They both have defined colour palettes.

**Comment by vpp** [comment]
Development branch tom-108-colors-for-leaves

**Comment by vpp** [comment]
Done. Merged to master.
