### ISSUE TITLE
Calendar feed not showing all future holidays

### ISSUE THREAD

**Issue by obyone** [timeoff-management/application#128]
I'm not sure if this is my understanding of how calendar feeds work or whether it is a bug.

I have subscribed to the calendar feed by importing the url taken from the 'Feeds' menu under the 'Me' heading.  I can see the first months worth of holidays from all the team members but nothing after that.

Is this the intended behaviour or do I need to make a configuration change?

I would love to be able to see the teams holidays in my Outlook / Fantastical calendar.

**Comment by vpp** [comment]
hi @obyone,

Application has two feeds:
* My Calendar page - feeds all data from My Calendar page
* Team view page - feeds Team view data for current month

In your case it sounds like you have subscribed to the Team view feed, which shows current month only at this moment.

Maybe it is worth extending team view calendar feed to more then one month.

If you hosting the app you can play with this on your own,here is where to start https://github.com/timeoff-management/application/blob/master/lib/route/feed.js#L70

**Comment by jekuno** [comment]
I agree it would be best if the Team View would at least cover a range of 2 years (1 year past and 1 year future). The preview is important for planning, the review helps to check who was off at which date or who e.g. participated in which offsite event.

**Comment by jekuno** [comment]
@obyon: @vpp already pointed you to the correct place. Diving deeper you find that the place you will have to change is https://github.com/timeoff-management/application/blob/master/lib/model/db/department.js#L106 

After looking at the source code I would suggest to reduce `CalendarMonth` to its bare minimum and to extract most of the prototype functions (such as `is_approved_leave` or `is_bank_holiday` into a `day` module).
Instead of using a `CalenderMonth` you will probably need to provide a `TwoYears` implementation which basically provides an own `as_for_template` implementation.

Alternatively you simply reuse the existing `CalendarMonth` collecting all leaves for each month. of the two years using `as_for_template`.

**Comment by vpp** [comment]
Good point towards @jekuno's suggestion: https://github.com/timeoff-management/application/issues/136#issuecomment-290420719

**Comment by madeinffm** [comment]
Hey everyone! Could anyone give me a hint what to insert on the given code to show a team calender for the next years?
Thanks!

**Comment by vpp** [comment]
Related patch is worked in `tom-128-calendar-feed-extended` branch.

**Comment by vpp** [comment]
I've merged some work related to feeds into *master*.

Now by default application exposes 6 future and 2 previous months; to override that behaviour please put `number_of_future_months_in_team_view_feed` and `number_of_past_months_in_team_view_feed` into `config/app.json` config file with corresponding numbers of months.
