### ISSUE TITLE
Allow special characters for bank holiday names

### ISSUE THREAD

**Issue by jekuno** [timeoff-management/application#132]
In Germany there is a bank holiday called "Buß- und Bettag".

Trying to add this Bak Holiday gives the following error: `New name of New Bank Holiday should contain only letters and numbers`

As e.g. "Buß- und Bettag" is an official bank holiday name both umlauts and hyphens should be allowed for names of bank holidays.

**Comment by vpp** [comment]
ouch..

Thanks for reporting

**Comment by vpp** [comment]
Initially there was an idea to store only "clean" data in DB.

But then I changed mind and decided to go with approach: allow users to store any data they want as long as it is rendered in safe way. And handlebar does it nicely. So that should protect from XSS attacks.

Regarding SQL injections, sequalise should take care about it.

So now the app does not restrict users from submitting only particular set of characters.

Hence this issue should be fixed.
