### ISSUE TITLE
No date picker on Team view

### ISSUE THREAD

**Issue by vpp** [timeoff-management/application#188]
When one opens Team view page and invoke Book timeoff modal and click on Start date filed, the date picker is not displayed properly.

This happens only in team view page.

**Comment by petrvecera** [comment]
This bug is caused by the fact that there are 2x leave dialog window rendered in the HTML. 

![image](https://user-images.githubusercontent.com/8086995/32499226-4dd4f630-c3d2-11e7-9457-08da816669c3.png)

One is from footer https://github.com/timeoff-management/application/blob/master/views/partials/footer.hbs#L2

Second on is from https://github.com/timeoff-management/application/blob/master/views/team_view.hbs#L73

But as you can see team view also includes footer L75, which adds the second dialog.

Made a PR with a fix.

**Comment by vpp** [comment]
@petrvecera thank you for fixing the issue.
