### ISSUE TITLE
Allowance usage per month report.

### ISSUE THREAD

**Issue by vpp** [timeoff-management/application#198]
We need to create new page with report that would allowance usage for employees.

The idea is inspired by PR https://github.com/timeoff-management/application/pull/192 done by @petrvecera as part of #184.

The new page would look like Team view, but instead of calendar grid there will be a table where
* rows are employees 
* columns are
** days deducted from allowance in current time period 
** one columns per leave type with number of days used from this leave type

It is possible to filter users by departments the same way Team View page does.

It is possible to change time frame of report
* change step is month
* default report - current month
* period of report mast start and end within single year

Report is accessible only by admin users.

Report is under new section "/reports/"

Optional:
* allow exporting report into CSV file

**Comment by petrvecera** [comment]
@vpp I have the export implemented. Unfortunately my fork is no longer in sync with master. Because I have used the function for calculating each user absence summary which I made for my team view summary.

But I guess you can inspire yourself https://github.com/timeoff-management/application/compare/master...petrvecera:exporter

I guess the most important things is the excel file generator https://github.com/timeoff-management/application/compare/master...petrvecera:exporter#diff-2089c57c88d8ba290e94e218cd4b0e93R770

Some screenshots of the feature:

![image](https://user-images.githubusercontent.com/8086995/33218878-94888428-d13f-11e7-9cae-3acebbd68947.png)

![image](https://user-images.githubusercontent.com/8086995/33218910-b83fd006-d13f-11e7-80f9-8b268f749171.png)


Multiple sheets are also supported 
![image](https://user-images.githubusercontent.com/8086995/33218899-ad76afa0-d13f-11e7-8d48-aa187cc38fc0.png)

**Comment by vpp** [comment]
@petrvecera thank you! Your help is great. I will definitely bring this into master

**Comment by petrvecera** [comment]
Hi @vpp , I just wanted to share our progress with you. Our accountant required comprehensive export. 

So now thanks to @znojProfiq we are able to generate such report:
![image](https://user-images.githubusercontent.com/8086995/35447569-5782d7e0-02b8-11e8-818b-382adb696921.png)

Unfortunately our fork is not compatible with master so we can't create a PR.  But I have created gist with the code https://gist.github.com/petrvecera/545b93008fee1da4ec3b5f412760c613 in case you would like to check it out. 

We experimented with several node modules for this and we think this is the best one for exporting the xls files https://www.npmjs.com/package/node-excel-export

**Comment by vpp** [comment]
hi @petrvecera, thank you for sharing ideas. THey proved to be really useful for the project.

I am not sure it is worth bringing Excel formatting into the project, .cvs should be sufficient for office people (HR etc) tp deal with data. I just want to keep set of dependencies to as small as possible.

BTW, I merged into master the first version of the report you've inspired: allowances usage by time frame. Still need to add statistics by leave time though.

**Comment by vpp** [comment]
Just added statistics by leave types.
