### ISSUE TITLE
New TLDs as email

### ISSUE THREAD

**Issue by saschafoerster** [timeoff-management/application#294]
I would like to use name@bonn.digital as our e-mail, but time off says, it is not a valid e-mail. So at least .digital should be added as a valid email, or all new TLDs could be accepted.

**Comment by JeffAlyanak** [comment]
@saschafoerster The current email validator is doing some naive regex testing rather than actually checking against a list of canonical TLDs.

The pull request I've submitted simply adjusts the regex to allow all the currently valid TLDs to be used, so you should apply that commit if you are urgently in need of using emails like `name@bonn.digital`.

**Comment by saschafoerster** [comment]
Great, thanks a lot!
