### ISSUE TITLE
Register New Company & Restore Links on Login Page

### ISSUE THREAD

**Issue by AsimPervez93** [timeoff-management/application#88]
Hi There, 

Regarding the register new company and restore links on the login page, I can see that in the login.hbs there is the following line:

<div class="col-md-4">
      <p class="pull-right"><a href="/forgot-password/">Forgot password?</a> {{#if allow_create_new_accounts }} | <a href="/register/">Register new company</a> | <a href="/import-company/">Restore</a>{{/if}}</p>
</div>

So I'm wondering if that "if allow create new accounts" parameter is working as I can always see these links when not logged in.

**Comment by vpp** [comment]
hi @AsimPervez93, the allow_create_new_accounts was recently added as some users do not want to allow multiple companies on their local installations. So they can hide the multitenant feature.

The "allow_create_new_accounts" flag is controlled via global config file. So in order to change the value one needs to update : https://github.com/timeoff-management/application/blob/master/config/app.json

So until you update the value in global config those links are always shown.

On other hand they should be able to restore the company from backup even  in single company mode.

So I think I will move the "Restore" link out of highlighted condition.

**Comment by vpp** [comment]
I just tweaked the code to always show "Restore" despite value of allow_create_new_accounts.

**Comment by AsimPervez93** [comment]
In my scenario, I am going to be the only person with authority to create new company's and restore so I do not want any other user to see those options.

I.e. I don't want the regular staff messing about with the restore funciton

**Comment by vpp** [comment]
@AsimPervez93, they will not be able to export/iport company without "admin" rights.

If you want them to prevent register new companies just set  "allow_create_new_accounts" flag to be false in config/app.json

**Comment by AsimPervez93** [comment]
Ah I see.

I'll do as you suggested and amend the config/app.json to prevent registering new companies.

Thanks very much for your advice.

**Comment by vpp** [comment]
no problems
